### ISSUE TITLE
'Issue child' broken in 1.4.0 and 1.4.1

### ISSUE THREAD

**Issue by lionleaf** [urbit/bridge#139]
"Issue child" page is just a white page with the following error in the console:
`Uncaught TypeError: f.azimuth.getUnspawnedChildren is not a function`
![image](https://user-images.githubusercontent.com/610925/57987543-9601c880-7a37-11e9-9f9c-882fe9415f56.png)

I have to revert to 1.3.1 to make it work.

**Comment by Fang-** [comment]
I... thought I fixed this in 1.4.1. Very strange, will take a look!

**Comment by Fang-** [comment]
Cannot reproduce on 1.4.1 as downloaded from the releases page, is this maybe a browser caching issue?

**Comment by lionleaf** [comment]
Weird, I've been running from the git repository, but did try 1.4.1 zip file release as well to confirm. I suspect I had caching issues when I did that, since the zipped version works now (taken care to disable caching).

The git version was still broken, but rerunning `npm run build` seems to have fixed it :|

False alarm ^^
