### ISSUE TITLE
I shouldn't see the option to generate Planet Codes while still on L1

### ISSUE THREAD

**Issue by jalehman** [urbit/bridge#750]
The following occurred on Brave from the star `~morzod` under `~zod`. 

1. I noticed the presence of the invite code icon in the upper right corner. This shouldn't be there while my star is still on L1.
<img width="554" alt="Screen Shot 2021-11-08 at 4 52 01 PM" src="https://user-images.githubusercontent.com/550978/140841896-58480e8f-2371-41f1-869e-0c7b76013fec.png">

2. Clicking into it goes to the Planet Codes menu:
<img width="545" alt="Screen Shot 2021-11-08 at 4 52 07 PM" src="https://user-images.githubusercontent.com/550978/140841931-9f80f0e2-aa79-4108-8074-3786f68d3306.png">

3. There's nothing that can be done on this screen:
<img width="1105" alt="Screen Shot 2021-11-08 at 4 52 36 PM" src="https://user-images.githubusercontent.com/550978/140842065-e25bb717-da9d-4764-879a-4053eb4ccac7.png">

4. Exiting the screen with the back button produces a loading spinner that I can't get out of.
<img width="806" alt="Screen Shot 2021-11-08 at 4 53 05 PM" src="https://user-images.githubusercontent.com/550978/140842099-648c0d28-bdfc-4a65-a050-596bdf311f87.png">

It seems that it shouldn't be possible to get to this state. When I try refreshing and jumping back in, there's no such menu, which leads me to believe that there's some sequence of actions that I can take that gets me to a place where the invite code menu is accessible.

**Comment by willbach** [comment]
@jalehman I fixed the bug where the page freezes, but there's still the question of if L1 stars should be able to generate invites. It is technically possible, so should the UX allow it or should generating invites be restricted to L2 stars?

**Comment by nerveharp** [comment]
![image](https://user-images.githubusercontent.com/748181/144631119-85a62508-1c34-4e63-bf37-e74e4db8c439.png)

Confirmed that I cannot see "Generate Invites" or any extant invites in the header of a newly-spawned, newly-keyed L1 star. I can still see invitations for ~hidzod and ~fogzod, but I assume these are leftover artifacts from testing.

![image](https://user-images.githubusercontent.com/748181/144631249-f9f8c6e7-0e48-4c27-a860-2bd98efae23f.png)
![image](https://user-images.githubusercontent.com/748181/144631325-e9915a01-743e-4b12-a868-ae5fba85b47e.png)

**Comment by willbach** [comment]
@nerveharp you can see invites for L1 stars with a spawn proxy set to L2. If you go into "ID" you can confirm this.

**Comment by nerveharp** [comment]
Got it, thank you. Maybe we do need a silly "L1.5" badge or something, but I feel like that's an edge case we can solve for later. I'll open a separate design issue.
